### ISSUE TITLE
Create a settings page

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#12]
We should create a settings page where users can 
 - Change their password
 - Change notification frequency (Always / only when page isn't focused / never)
 - Change their user's color (If we add it)
 - Change their profile picture (If we add it)

**Comment by spaceface777** [comment]
@magnitopic and @KeyKoder are working on it.

**Comment by magnitopic** [comment]
And replace the LogOut button with the Settings and include LogOut inside the Settings page

**Comment by ThePerkinrex** [comment]
From 071e7be5d79fc9925192d5ab6b5780c49ce56ec9 to 32606388b18d00e9cfc20eb8aa508d8fc5a45cb5, all the commits have been for implementing this

**Comment by ThePerkinrex** [comment]
When this issue is closed, Hermes v3.0.0 will be ready for release
