### ISSUE TITLE
Add ability to tag (@) other users

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#13]

**Comment by spaceface777** [comment]
Duplicate of #6

**Comment by spaceface777** [comment]
> Duplicate of #6

In the end, although #6 had two parts, we only implemented the second one and not this one.

**Comment by Tloru** [comment]
mentioning would just be quoting without the reference message, right? Couldn't we just extend the quote regex and update on the GUI?

**Comment by ThePerkinrex** [comment]
Yes, probably that could be the solution

**Comment by ThePerkinrex** [comment]
I will look into it

**Comment by spaceface777** [comment]
Another option would be to add another regex (`@([^ ]+)` for example), check if the matched string is in the `user_colors` object, and if it is replace the whole thing with a formatted version of the string: 

```html
<b style="color: #color">regex[1]</b>
```

**Comment by spaceface777** [comment]
Most of the work has been done in 3a28db4.
