### ISSUE TITLE
Add multiple chat pages, like groups or channels

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#14]
This would add pages located in `/chat/%channel_uuid%` and for all the APIs related to sending & recieving messages, like `/loadmessages` would have `/%channel_uuid%` attached to the end.
In redis we could store them as a list named `%channel_uuid%_messages`

**Comment by ThePerkinrex** [comment]
Will be worked on with the implementation of cassandra

**Comment by ThePerkinrex** [comment]
with the implementation of cassandra, the database infrastructure to make it happen is already in place

**Comment by ThePerkinrex** [comment]
This is being worked on by @KeyKoder (I think)

**Comment by ThePerkinrex** [comment]
This has been worked on on the front end, but the backend won't be ready until the DB redesign

**Comment by ThePerkinrex** [comment]
Backend work is being done on the chats branch
Anyone that wants to work on it is more than welcome

**Comment by spaceface777** [comment]
We've been working on this for the last few days, and most of it has been finished in 7140cb6

**Comment by spaceface777** [comment]
Done.
