### ISSUE TITLE
Make the web pages responsive so that they can be used on mobile

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#15]

**Comment by ThePerkinrex** [comment]
This would help when creating the mobile app

**Comment by Tloru** [comment]
Line spacing also seems to be hard set at load-time, when resizing, you can run into issues like this:
![screen shot 2019-02-12 at 6 14 53 pm](https://user-images.githubusercontent.com/17747189/52631738-2c32c980-2ef2-11e9-8935-58b80584cdb3.png)
or like this (the time obscures the messages):
![screen shot 2019-02-12 at 6 16 11 pm](https://user-images.githubusercontent.com/17747189/52631782-4f5d7900-2ef2-11e9-8800-88df55738742.png)
These look like a few quick fixes, just wanted to let y'all know. I'll point out anything else that I notice, if that's alright with you.

**Comment by ThePerkinrex** [comment]
This is being fixed with the redesign

**Comment by Tloru** [comment]
@ThePerkinrex I think that this has been mostly fixed in the redesign, at the moment, a screen as small as 250x100px is usable (albeit hard to use).

**Comment by spaceface777** [comment]
There are still some issues with the settings page, though, and I am still working on improvements to make it more usable on small screens.

**Comment by spaceface777** [comment]
This is pretty much finished (apart from #83)
