### ISSUE TITLE
Anyone can send messages through the API without need for login

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#16]

**Comment by spaceface777** [comment]
How should we solve this?

**Comment by ThePerkinrex** [comment]
We could generate a key or uuid, and store it in a list with all the logged in users uuids/keys, and remove it from the list when they log out, and to join the chat & send messages you're asked for it to send it

**Comment by ThePerkinrex** [comment]
Probably fixed in [b9c5322e599e566f12a753a9c1225eb4179f3e23](https://github.com/HermesMessenger/Hermes/commit/b9c5322e599e566f12a753a9c1225eb4179f3e23)
