### ISSUE TITLE
Login isn't secure

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#19]
Right now, the only thing the login page does is set the username cookie. Any user can set the cookie to anything, go to [server.com/chat](https://server.com/chat) and be logged in as any user they want.

**Comment by VladyslavLukyanenko** [comment]
What about an Authorization: Bearer header with email:pass in aes

**Comment by ThePerkinrex** [comment]
Probably fixed in [b9c5322e599e566f12a753a9c1225eb4179f3e23](https://github.com/HermesMessenger/Hermes/commit/b9c5322e599e566f12a753a9c1225eb4179f3e23)
