### ISSUE TITLE
Make links work as links

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#21]
We should make links work as actual links, so a user can click them and they open in a new tab.

**Comment by ThePerkinrex** [comment]
This would need actual parsing of the message to make it work

**Comment by spaceface777** [comment]
We can use a regular expression for this, for example: 

```regexp
(http:\/\/|https:\/\/)(.+)(\.)(.+)
```

**Comment by spaceface777** [comment]
And we already parse the messages to find quotes in them.
