### ISSUE TITLE
If user doesn't log out the uuid is kept in the db, but not used

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#26]
This is a problem, because infinite uuid's could be stored.
It could be fixed by adding a maximum usable time to logged in user uuids.
Or if a user logs in and it already has a uuid created(because he/she didn't log out), use that uuid

**Comment by spaceface777** [comment]
To solve this **I** would add the time when a UUID is created to the DB so it would look like this: ```user + SEPCHAR + user_uuid + creation_time```.   
Then, every time the user does something with Hermes (send a message, get messages...) I would change the creation time to the current time.

**Comment by ThePerkinrex** [comment]
That's a good solution
