### ISSUE TITLE
Quotes don't work when replying to a message with a quote in it

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#27]
The quote doesn't parse the text correctly and shows it as empty. 
![image](https://user-images.githubusercontent.com/12110214/48479806-adea5c80-e808-11e8-9ad0-e00c0e9e6b69.png)

**Comment by ThePerkinrex** [comment]
Quotes should be ignored when quoting  a message

**Comment by spaceface777** [comment]
Fixed by @KeyKoder in ea3dd9f
