### ISSUE TITLE
There can be HTML tags inside a link

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#31]
This problem can still happen inside links:

![image](https://user-images.githubusercontent.com/12110214/48622282-87622800-e9a6-11e8-9515-83c569bd3f9b.png)
![image](https://user-images.githubusercontent.com/12110214/48622304-9c3ebb80-e9a6-11e8-810d-af29171f4e4b.png)

**Comment by ThePerkinrex** [comment]
This is because in line 124 of index.js, we're just appending the string, instead of doing .text

**Comment by ThePerkinrex** [comment]
`let link_span = ("<a target=\'_blank\' href = \'") + match2[0] + "\'> " + match2[0] + "</a>";`

**Comment by ThePerkinrex** [comment]
Fixed on 3f80b81
