### ISSUE TITLE
Quoting messages with links doesn't work properly

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#33]
![image](https://user-images.githubusercontent.com/19746634/48633503-c18df280-e9c3-11e8-85be-bab15cdff308.png)

The link does not appear and the quote is not marked as one

**Comment by spaceface777** [comment]
It only selects the text until the quote: 

![image](https://user-images.githubusercontent.com/12110214/48665692-6dfad200-eab3-11e8-8f7d-b50cce768210.png)

**Comment by ThePerkinrex** [comment]
- now selecting a message with a link works
 - a quote with a link inside works but the text behind it doesn't
 - a quote with text before works
 - a quote with a link before it doesn't work (Something really weird happens, see image) 

![image](https://user-images.githubusercontent.com/19746634/50702053-0b07cf00-1050-11e9-80aa-dc99369f019d.png)

**Comment by ThePerkinrex** [comment]
If you want's to continue working on this just assign yourself instead of me

**Comment by ThePerkinrex** [comment]
The problem is that it counts how many links there are in the message, regardless if they're inside the quote
so it goes through the loop and pretends there are more links, pasting itself & then when it has finished  the quote is written

**Comment by ThePerkinrex** [comment]
This should be fixed along with #48

**Comment by spaceface777** [comment]
Yes, it's fixed.
