### ISSUE TITLE
Time is always the same even if the time zone of the client is different

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#34]
Since the message time is added server side, the times of the messages depend on the time zone where the server is located. (It can be a problem when we present it in Dublin)

To fix this, we can make the server store the time in UTC format and then convert it on the client depending on its location.

**Comment by ThePerkinrex** [comment]
I think now it's fixed, because the date is sent from the server as a timestamp and the converted in the client to a javascript Date object.
This object, I think, when using .getHour() and all the other .get functions, returns from local time, not UTC time.

**Comment by spaceface777** [comment]
Confirming that the issue is solved.
