### ISSUE TITLE
Quotes sometimes display " at the end

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#35]
This happens sometimes, but I haven't looked into what might cause them
<img width="641" alt="captura de pantalla 2018-11-19 a las 14 32 45" src="https://user-images.githubusercontent.com/19746634/48710326-3487ab00-ec08-11e8-8ab9-d37c9ca289fd.png">
^^^^^^^^^^^^^^^^^^^^^^^
It looks like it might be related to how we parse qouted messages without quotes & the difference to how we parse then when the quoted messages have quotes.

**Comment by ThePerkinrex** [comment]
I think it's fixed on testing

**Comment by spaceface777** [comment]
> I think it's fixed on testing

The issue is still present. The characters that cause the issue are all the regexp special characters (`\ ^ $ . | ? * + ( ) { } [ ]`) except for `.` (?)

**Comment by ThePerkinrex** [comment]
fixed on 0435f3f
