### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#39]
This would help the Hermes Desktop app, and fix [#1](https://github.com/HermesMessenger/HermesDesktop/issues/1) from there. In that issue there's a bit more explained, but it would basicly mean to add a `/dark` to every page

**Comment by spaceface777** [comment]
We can also create a cookie (`DarkMode` for example), and if the server receives the cookie it sends the dark page instead of the normal one. 

I think this would be easier than making two copies of each page.

**Comment by ThePerkinrex** [comment]
Working on it

**Comment by ThePerkinrex** [comment]
There are many css files in need of updating for dark mode, if anyone wants to it would greatly help to update more files

**Comment by ThePerkinrex** [comment]
The only thing left is the login/register page, which needs to be included in the redesign, because now it doesn't fit with the others

**Comment by ThePerkinrex** [comment]
This is done
