### ISSUE TITLE
Add browser notifications

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#4]
Add an option to show a notification when a new message is sent. 

There are [many libraries](https://thecodebarbarian.com/sending-web-push-notifications-from-node-js.html) which can help us do this.

**Comment by ThePerkinrex** [comment]
Done in commit [5c0b443](https://github.com/HermesMessenger/Hermes/commit/5c0b443333f54f7962b21c83b0bd50229337bcd1) marking as closed
