### ISSUE TITLE
Time does not show padding after Cassandra implementation

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#41]
I don't know if we changed the function that generated it, but it was better like before.

![Screenshot](https://user-images.githubusercontent.com/12110214/49337768-c33cf480-f618-11e8-828f-0c4f43f3d28a.png)

**Comment by ThePerkinrex** [comment]
The function was changed because now it uses a date object. Maybe we can create a function that adds a zero to a number of its below 10

**Comment by ThePerkinrex** [comment]
✅  Fixed on ad61322
