### ISSUE TITLE
Message size on mobile

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#42]
There are a few problems with message sizes on mobile:

 - The time is too small to read
 - The first few messages are very small, but then it corrects itself after a few. 
    - If you rotate the device, all of them show with the same (big) font size. 

![Screenshot](https://user-images.githubusercontent.com/12110214/49337784-2464c800-f619-11e8-9209-dd976c60d415.png)

**Comment by ThePerkinrex** [comment]
Duplicate of #15
