### ISSUE TITLE
Show date and time a message was sent

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#5]
Right now a user doesn't have a way of seeing when a message was sent. The UI might look something like this:

![image](https://user-images.githubusercontent.com/12110214/48147762-5738cc00-e2b8-11e8-96f1-cd5fcad1cc9e.png)

**Comment by ThePerkinrex** [comment]
I think @KeyKoder  was working on this, do I mark him as an assigned?

**Comment by ThePerkinrex** [comment]
*assignee

**Comment by spaceface777** [comment]
Fixed
