### ISSUE TITLE
Make quotes link to the original message

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#53]
For linking, the messages already have an id, `message_` with `_` being the number of message, so to link to it, we should redirect to the same page but with `#message_` at the end

**Comment by spaceface777** [comment]
This should be split into two issues (*because I'm implementing the second suggestion now*)

**Comment by ThePerkinrex** [comment]
closed in theperkinrex-md-impl branch

**Comment by ThePerkinrex** [comment]
This is fixed on testing, but the animations need to be worked on, because it highlights the message even if its not on screen, & it tries to animate the messages to the top of the screen
