### ISSUE TITLE
Go to top arrow shows when setings is activated 

### ISSUE THREAD

**Issue by magnitopic** [HermesMessenger/Hermes#55]
When u open the settings menu and scroll up the go-to top arrow pops up on top of the settings page.

**Comment by spaceface777** [comment]
For me it doesn't appear either

**Comment by magnitopic** [comment]
Bug fixed in version 3.0.0 by KeyKoder

**Comment by magnitopic** [comment]
Bug fixed in version 3.0.0 by KeyKoder
