### ISSUE TITLE
Make the first message load use the faster old method

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#56]
As it has to load all the messages anyway, let's use the older method, as it's faster

**Comment by ThePerkinrex** [comment]
Maybe this could be just fixed by making a load animation, that is over the entire thing until the messages have loadded

**Comment by spaceface777** [comment]
I don't think this is needed anymore since we already have a loading animation and #82 would pretty much stop this from being an issue.
