### ISSUE TITLE
Fix perfomance issues when deleting/editing messages

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#59]
Mainly it is not loading all the messages all the time, but saveing in the server the ID, an sending the ones that have been deleted & edited
***
*I was really tired when I wrote this, even I don't understand what it tries to say*

**Comment by ThePerkinrex** [comment]
Should be fixed in 3924776ab58165b884cb2a2e0e2c357d948c86e6

**Comment by ThePerkinrex** [comment]
If the fix doesn't have any mayor issues, v3.0.0 should be ready

**Comment by spaceface777** [comment]
I think we should wait until #60 is closed before releasing v3.0.0 since it is a major issue.

**Comment by ThePerkinrex** [comment]
Yes, I forgot about that, but we should fix that pretty soon
