### ISSUE TITLE
People can edit and delete messages sent by other users

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#60]
To fix this, we should add server and client side verification in this process.

***

Although this issue could be included in #59, I think it is important enough to have its own issue.

**Comment by ThePerkinrex** [comment]
And if you edit someone else's message it changes the username to yours

**Comment by ThePerkinrex** [comment]
ece199c should have fixed this issue, both in the server, and in the client (the client fix is only for prettyness)
