### ISSUE TITLE
Some messages get duplicated

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#63]
I have no idea what's causing the issue, we have to look into it. 

![image](https://user-images.githubusercontent.com/12110214/52489525-c75e3300-2bc2-11e9-9ee6-4d2ffe4b896a.png)

**Comment by ThePerkinrex** [comment]
This could be fixed by checking when loading a message if a message with that UUID already exists

**Comment by Tloru** [comment]
@spaceface777 I've run into that issue too, it tends to be fixed by reloading and only applies to new messages. I think this might be because the message is being added twice to the DOM when a new one is received, although I have no idea how this is happening.

**Comment by spaceface777** [comment]
The issue happens because of how we load messages. We send a POST request to the server every 500ms with the id of the last message loaded, and the server sends back the messages that were added since that one. If the client disconnects from the Internet for some reason, then it'll send more than one request with the same id, and when it receives all the responses together the client thinks they are all individual messages and not the same ones but duplicated. 

This could be fixed like @ThePerkinrex said: by checking if the message it's about to load already exists, and stop loading it if it is already shown.

**Comment by spaceface777** [comment]
@ThePerkinrex fixed this already.
