### ISSUE TITLE
Remove ALLOW FILTERING from DB queries

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#65]
Some of our database queries use `ALLOW FILTERING` to get the results from the query, which is a major performance issue (more info [here](https://www.datastax.com/dev/blog/allow-filtering-explained-2)). 

Fixing this issue requires changing the DB schema, so we will have to wipe the database when solving this.

**Comment by ThePerkinrex** [comment]
This will be closed with a new DB-Schema, as the current one hasn't been designed thoroughly enough

**Comment by spaceface777** [comment]
This is implemented with the new DB schema.
