### ISSUE TITLE
Use Sans-Serif font instead of Monospaced Font. 

### ISSUE THREAD

**Issue by Tloru** [HermesMessenger/Hermes#70]
I like the Monospaced font, ngl, but I think a sans-serif (preferably humanist) font, such as [Roboto](https://fonts.google.com/specimen/Roboto), [Lato](https://fonts.google.com/specimen/Lato), [Source Sans Pro](https://fonts.google.com/specimen/Source+Sans+Pro), or [PT-Sans](https://fonts.google.com/specimen/PT+Sans) might easier on the eyes.

**Comment by Tloru** [comment]
here's the proposed dark theme with PT Sans, for example: 
![screen shot 2019-02-14 at 6 58 31 pm](https://user-images.githubusercontent.com/17747189/52785454-9da58000-308a-11e9-9457-bde5e5f5084f.png)

**Comment by spaceface777** [comment]
Pretty much the same thing I said in [#69](https://github.com/HermesMessenger/Hermes/pull/69#issuecomment-476386721): you can add your own theme with a different font.
