### ISSUE TITLE
Extra Dates at Bottom of Screen

### ISSUE THREAD

**Issue by Tloru** [HermesMessenger/Hermes#74]
I first noticed this happening after the double message was fixed. 

When you open hermes, you'll find a list of dates at the bottom. I have seen from 2 to 4:
![screen shot 2019-02-18 at 5 29 05 am](https://user-images.githubusercontent.com/17747189/52920401-6828bd00-333e-11e9-8161-775b088a7be2.png)

If you send a message, these dates move up:
![screen shot 2019-02-18 at 5 29 23 am](https://user-images.githubusercontent.com/17747189/52920403-724abb80-333e-11e9-918f-4d873eb7be07.png)

But if you reload, they go back to the bottom:
![screen shot 2019-02-18 at 5 29 40 am](https://user-images.githubusercontent.com/17747189/52920408-7c6cba00-333e-11e9-8b90-7ddff53b01f7.png)

Just a quick pointer 😄

**Comment by spaceface777** [comment]
The fix for this is the same as that of the message duplication issue: checking if the date element already exists before printing it.
