### ISSUE TITLE
Make the quotes not a literal part of the message

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#79]
We should make the quotes be on top of the message sending form, and add them as a link to the original message (with the id), and when editing only add the ability to delete it

**Comment by spaceface777** [comment]
@KeyKoder implemented part of this.

**Comment by ThePerkinrex** [comment]
The message could only include a text mentioning the message uuid of the original, like
`"message-f3bb8a00-42a2-11e9-b473-47ff2bf067fa" Hi` 
This is how it should be stored in the database, but the client shouldn't see it when writing or editing the message.
Also the quote should update with the message

**Comment by ThePerkinrex** [comment]
With the new performance fix, the quotes are broken, so maybe with this issue we could fix that as well

**Comment by ThePerkinrex** [comment]
Most of this is fixed
The only thing left is putting the quote above the message textarea

**Comment by ThePerkinrex** [comment]
✅  Fixed on 5b41e6b64dbb247219d64e5b363b562033027050 and beyond
