### ISSUE TITLE
Improve the performance of the site

### ISSUE THREAD

**Issue by spaceface777** [HermesMessenger/Hermes#83]
The site feels **very** slow, especially on mobile, and this causes many annoying things: 

 - Text sometimes takes a while to appear in the input box
 - The animations feel very slow
 - Scrolling up and down causes stutters
 - Loading the app for the first time takes a very long time

***

**TL,DR:** We should really try to improve the performance of the site

**Comment by ThePerkinrex** [comment]
This should be fixed on testing
Waiting for approval of the team

**Comment by spaceface777** [comment]
Yes, all the major problems have been fixed.
