### ISSUE TITLE
Add support to upload images to hermes

### ISSUE THREAD

**Issue by Tloru** [HermesMessenger/Hermes#94]
possibilities:

- host images on hermes server
- use an external service

**Comment by ThePerkinrex** [comment]
Maybe we could add it as part of the markdown
`![img_link]`

**Comment by ThePerkinrex** [comment]
Like github

**Comment by spaceface777** [comment]
> Maybe we could add it as part of the markdown
> `![img_link]`

Most of this was implemented in 20860f9.
