### ISSUE TITLE
The API doesn't check whether a user is in a channel before processing the request

### ISSUE THREAD

**Issue by ThePerkinrex** [HermesMessenger/Hermes#98]
The title describes the issue

**Comment by spaceface777** [comment]
Users can also load messages from channels they aren't in, we should add a check to see if the user is in the channel and return 404 if they aren't.

**Comment by ThePerkinrex** [comment]
Yep

**Comment by spaceface777** [comment]
This is also not _that_ big of an issue since if you know the channel UUID you can join it anyways

**Comment by ThePerkinrex** [comment]
Yeah, but still...
